# Generated by Django 5.1.13 on 2025-10-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_responsable', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('horario_disponible', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, unique=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('puntuacion_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concursos_creados', to='Concursos_Online.administrador')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concursos_ganados', to='Concursos_Online.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Asigna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asigna_concurso', to='Concursos_Online.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.PositiveIntegerField(default=0)),
                ('especialidad', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('puntuacion_media', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('concursos', models.ManyToManyField(related_name='jurados', through='Concursos_Online.Asigna', to='Concursos_Online.concurso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jurado', to='Concursos_Online.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_jurado', to='Concursos_Online.jurado')),
            ],
        ),
        migrations.AddField(
            model_name='asigna',
            name='jurado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asigna_jurado', to='Concursos_Online.jurado'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to='Concursos_Online.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Inscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscribe_concurso', to='Concursos_Online.concurso')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscribe_participante', to='Concursos_Online.participante')),
            ],
        ),
        migrations.AddField(
            model_name='concurso',
            name='participantes',
            field=models.ManyToManyField(related_name='inscritos', through='Concursos_Online.Inscribe', to='Concursos_Online.participante'),
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('puntuacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajo_concurso', to='Concursos_Online.concurso')),
                ('jurados', models.ManyToManyField(related_name='trabajos_evaluados', through='Concursos_Online.Evaluacion', to='Concursos_Online.jurado')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajo_participante', to='Concursos_Online.participante')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_trabajo', to='Concursos_Online.trabajo'),
        ),
        migrations.CreateModel(
            name='Recibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('EN', 'Enviada')], default='PE', max_length=2)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='Concursos_Online.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='Concursos_Online.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('imagen_perfil', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='Concursos_Online.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participante', to='Concursos_Online.usuario'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuarios',
            field=models.ManyToManyField(related_name='notificaciones_recibidas', through='Concursos_Online.Recibe', to='Concursos_Online.usuario'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='Concursos_Online.usuario'),
        ),
    ]
