# Generated by Django 5.1.13 on 2025-10-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concursos_Online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='puntuacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
