# Generated by Django 5.1.14 on 2025-11-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concursos_Online', '0002_alter_evaluacion_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='usuarios/default.jpg', null=True, upload_to='usuarios/'),
        ),
    ]
